baseurl = "/"
theme = "soho"
languageCode = "es-es"
title = "Juan Carrey"

pygmentsUseClasses = true
disqusShortname = "juan-carrey"
googleAnalytics = "UA-177421585-1"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true

[params]
author = "Juan Carrey"
description = "Software Engineering"

## Set one of:
# gravatar = "soho@example.com"
profilePicture = "images/profile.webp"

copyright = "Author Name"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

## Set custom theme color.
# themeColor = "#fc2803"

## Set custom CSS and/or JS to override site defaults.
# customCss = ["css/blog.css"]
# customJs = ["js/blog.js"]

## Set as many as you want.
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://es.linkedin.com/in/juancarrey"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/juancarrey/"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/jcarreyz"

[menu]

[[menu.main]]
name = "Posts"
weight = 100
identifier = "posts"
url = "/posts/"

[[menu.main]]
name = "About"
identifier = "about"
weight = 300
url = "/about/"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[markup]

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true # if false, you need to provide you own custom CSS
style = "monokai"
tabWidth = 4
